// Code generated by "stringer -type=Status -linecomment"; DO NOT EDIT.

package gsandbox

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnset-0]
	_ = x[StatusOK-1]
	_ = x[StatusTimeLimitExceeded-2]
	_ = x[StatusMemoryLimitExceeded-3]
	_ = x[StatusOutputLimitExceeded-4]
	_ = x[StatusViolation-5]
	_ = x[StatusSignaled-6]
	_ = x[StatusExitFailure-7]
}

const _Status_name = "unsetoktime limit execeededmemory limit exceededoutput limit exceededsyscall violationterminated with a signalexit with nonzero code"

var _Status_index = [...]uint8{0, 5, 7, 27, 48, 69, 86, 110, 132}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
