// Code generated by "stringer -type=FlagOpenConstant -output=flags_constants_open_string.go"; DO NOT EDIT.

package ptrace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[O_RDONLY-0]
	_ = x[O_WRONLY-1]
	_ = x[O_RDWR-2]
	_ = x[O_APPEND-1024]
	_ = x[O_ASYNC-8192]
	_ = x[O_CLOEXEC-524288]
	_ = x[O_CREAT-64]
	_ = x[O_DIRECT-16384]
	_ = x[O_DSYNC-4096]
	_ = x[O_EXCL-128]
	_ = x[O_NOATIME-262144]
	_ = x[O_NOCTTY-256]
	_ = x[O_NONBLOCK-2048]
	_ = x[O_PATH-2097152]
	_ = x[O_SYNC-1052672]
	_ = x[O_TMPFILE-4259840]
	_ = x[O_TRUNC-512]
}

const _FlagOpenConstant_name = "O_RDONLYO_WRONLYO_RDWRO_CREATO_EXCLO_NOCTTYO_TRUNCO_APPENDO_NONBLOCKO_DSYNCO_ASYNCO_DIRECTO_NOATIMEO_CLOEXECO_SYNCO_PATHO_TMPFILE"

var _FlagOpenConstant_map = map[FlagOpenConstant]string{
	0:       _FlagOpenConstant_name[0:8],
	1:       _FlagOpenConstant_name[8:16],
	2:       _FlagOpenConstant_name[16:22],
	64:      _FlagOpenConstant_name[22:29],
	128:     _FlagOpenConstant_name[29:35],
	256:     _FlagOpenConstant_name[35:43],
	512:     _FlagOpenConstant_name[43:50],
	1024:    _FlagOpenConstant_name[50:58],
	2048:    _FlagOpenConstant_name[58:68],
	4096:    _FlagOpenConstant_name[68:75],
	8192:    _FlagOpenConstant_name[75:82],
	16384:   _FlagOpenConstant_name[82:90],
	262144:  _FlagOpenConstant_name[90:99],
	524288:  _FlagOpenConstant_name[99:108],
	1052672: _FlagOpenConstant_name[108:114],
	2097152: _FlagOpenConstant_name[114:120],
	4259840: _FlagOpenConstant_name[120:129],
}

func (i FlagOpenConstant) String() string {
	if str, ok := _FlagOpenConstant_map[i]; ok {
		return str
	}
	return "FlagOpenConstant(" + strconv.FormatInt(int64(i), 10) + ")"
}
