// Code generated by "stringer -type=FlagFcntlCmdConstant -output=flags_constants_fcntl_cmd_string.go"; DO NOT EDIT.

package ptrace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[F_DUPFD-0]
	_ = x[F_GETFD-1]
	_ = x[F_SETFD-2]
	_ = x[F_GETFL-3]
	_ = x[F_SETFL-4]
	_ = x[F_GETLK-5]
	_ = x[F_SETLK-6]
	_ = x[F_SETLKW-7]
	_ = x[F_SETOWN-8]
	_ = x[F_GETOWN-9]
	_ = x[F_SETSIG-10]
	_ = x[F_GETSIG-11]
	_ = x[F_SETOWN_EX-15]
	_ = x[F_GETOWN_EX-16]
	_ = x[F_DUPFD_CLOEXEC-1030]
	_ = x[F_SETPIPE_SZ-1031]
	_ = x[F_GETPIPE_SZ-1032]
}

const (
	_FlagFcntlCmdConstant_name_0 = "F_DUPFDF_GETFDF_SETFDF_GETFLF_SETFLF_GETLKF_SETLKF_SETLKWF_SETOWNF_GETOWNF_SETSIGF_GETSIG"
	_FlagFcntlCmdConstant_name_1 = "F_SETOWN_EXF_GETOWN_EX"
	_FlagFcntlCmdConstant_name_2 = "F_DUPFD_CLOEXECF_SETPIPE_SZF_GETPIPE_SZ"
)

var (
	_FlagFcntlCmdConstant_index_0 = [...]uint8{0, 7, 14, 21, 28, 35, 42, 49, 57, 65, 73, 81, 89}
	_FlagFcntlCmdConstant_index_1 = [...]uint8{0, 11, 22}
	_FlagFcntlCmdConstant_index_2 = [...]uint8{0, 15, 27, 39}
)

func (i FlagFcntlCmdConstant) String() string {
	switch {
	case 0 <= i && i <= 11:
		return _FlagFcntlCmdConstant_name_0[_FlagFcntlCmdConstant_index_0[i]:_FlagFcntlCmdConstant_index_0[i+1]]
	case 15 <= i && i <= 16:
		i -= 15
		return _FlagFcntlCmdConstant_name_1[_FlagFcntlCmdConstant_index_1[i]:_FlagFcntlCmdConstant_index_1[i+1]]
	case 1030 <= i && i <= 1032:
		i -= 1030
		return _FlagFcntlCmdConstant_name_2[_FlagFcntlCmdConstant_index_2[i]:_FlagFcntlCmdConstant_index_2[i+1]]
	default:
		return "FlagFcntlCmdConstant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
