// Code generated by "stringer -type=ParamType -output=syscall_paramtype_string.go"; DO NOT EDIT.

package ptrace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParamTypeAny-0]
	_ = x[ParamTypeInt-1]
	_ = x[ParamTypePath-2]
	_ = x[ParamTypePipeFd-3]
	_ = x[ParamTypeFd-4]
	_ = x[ParamTypeFlagOpen-5]
	_ = x[ParamTypeFlagFnctlCmd-6]
}

const _ParamType_name = "ParamTypeAnyParamTypeIntParamTypePathParamTypePipeFdParamTypeFdParamTypeFlagOpenParamTypeFlagFnctlCmd"

var _ParamType_index = [...]uint8{0, 12, 24, 37, 52, 63, 80, 101}

func (i ParamType) String() string {
	if i < 0 || i >= ParamType(len(_ParamType_index)-1) {
		return "ParamType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParamType_name[_ParamType_index[i]:_ParamType_index[i+1]]
}
